
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import "mdb-react-ui-kit/dist/css/mdb.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import LazyLoadComponent from "./utils/LazyLoadComponent ";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Solvify Technologies",
  description: "Generated by Solvify Technologies",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="page">
        <LazyLoadComponent>{children}</LazyLoadComponent>
      </body>
    </html>
  );
}
